[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "EXAMPLE"
version = "0.0.1"
description = "EXAMPLE"
authors = [{ name="CraftsByFrayJay" }]
dependencies = []

[project.scripts]
EXAMPLE = "EXAMPLE.cli:main"
