[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "RepoGuard"
version = "0.0.1"
description = "Simple CLI tool to check basic repository health"
authors = [{ name="CraftsByFrayJay" }]
dependencies = []

[project.scripts]
repoguard = "app.cli:main"
